// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'article__date': string;
  'articles__title': string;
  'button': string;
  'salary': string;
  'vacancies': string;
  'vacancy': string;
  'vacancy__button': string;
}
export const cssExports: CssExports;
export default cssExports;
