version: "3"
services:
  postgres:
    image: postgres:14.7-alpine
    ports:
      - "5433:5433"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev

  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - app
  api:
    build: .
    depends_on:
      - postgres
    command: uvicorn main:app
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev

volumes:
  postgres_data:
