version: "3"
services:
  # postgres:
  #   image: postgres:14.7-alpine
  #   ports:
  #     - "5433:5433"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data/
  #   env_file:
  #     - ./.env.dev

  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - api
  api:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000
    
# volumes:
#   postgres_data:
