version: "3.9"
services:
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - api
  api:
    build: ./backend
    command: uvicorn src.index:app --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000
