version: "3.6"
services:
  nginx:
    build: ./nginx
    ports:
      - 1337:1337
    depends_on:
      - api
  api:
    build: ./backend
    command: uvicorn src.index:app --host 0.0.0.0 --port 80
    ports:
      - 8000:8000
