version: "3.6"
services:
  api:
    hostname: api
    container_name: "api"
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: uvicorn src.index:app --host 0.0.0.0  --port 8080
    ports:
      - 8080:8080
    volumes:
      - ./backend:/app

  frontend:
    hostname: frontend
    container_name: frontend
    depends_on:
      - api
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
  nginx:
    hostname: nginx
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
    depends_on:
      - api
    volumes:
      - ./nginx:/etc/nginx/conf.d
