// This file is automatically generated.
// Please do not change this file!
interface CssExports {
	profile: string;
	profile__date: string;
	profile__email: string;
	profile__isactiv: string;
	profile__name: string;
	profile__username: string;
}
export const cssExports: CssExports;
export default cssExports;
