// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'panel': string;
  'panel__icon': string;
  'panel__link': string;
  'panel__title': string;
}
export const cssExports: CssExports;
export default cssExports;
