// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'article__body': string;
  'article__button': string;
  'article__title': string;
  'button': string;
  'error': string;
  'form-control': string;
  'form-wrapper': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
