"""Database creation

Revision ID: 7e7f81e71c03
Revises: 3326f42c73eb
Create Date: 2023-10-13 12:10:27.142629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e7f81e71c03'
down_revision: Union[str, None] = '3326f42c73eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('author_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'article', 'user', ['author_id'], ['id'])
    op.drop_constraint('user_article_id_fkey', 'user', type_='foreignkey')
    op.drop_column('user', 'article_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('article_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('user_article_id_fkey', 'user', 'article', ['article_id'], ['id'])
    op.drop_constraint(None, 'article', type_='foreignkey')
    op.drop_column('article', 'author_id')
    # ### end Alembic commands ###
