// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'profile__container': string;
  'profile__content': string;
  'profile__panel': string;
}
export const cssExports: CssExports;
export default cssExports;
