// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button': string;
  'error': string;
  'form': string;
  'form-wrapper': string;
  'title': string;
  'wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
