name: Build and deploy action
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: |
          cd frontend 
          npm ci
      - name: Lint application
        run: |
          cd frontend
          npm run lint

      # - name: Test
      #   run: |
      #     pwd
      #     cd frontend
      #     pwd
      #     npm run test

      - name: Build application
        run: |
          cd frontend
          npm run build -y
