name: Build and deploy action
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          cd frontend 
          npm ci
      # - name: Test
      #   run: |
      #     pwd
      #     cd frontend
      #     pwd
      #     npm run test
  lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          cd frontend 
          npm ci
      - name: Lint application
        run: |
          cd frontend
          npm run lint

  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Build application
        run: |
          cd frontend
          npm run build
